discordbot/slashcommandeventclasses/stats.py
discordbot/views/wrapped.py

- Added a wrapped view
- View button shares the message publicly

Add a share button for Wrapped22 (#188)

---

discordbot/tasks/wordletask.py

Changed the wordle logic so that it's less dependent on a particular time

Trigger wordle if we missed it (#210)

---

discordbot/clienteventclasses/onmessageedit.py

- Add some debug information for message edit

Message edit debug #225

---

discordbot/tasks/wordletask.py
discordbot/wordle/wordlesolver.py

- add word frequency data
- use word frequency data as weightings in random.choices for picking words

#183 Wordle solving improvements

---

discordbot/clienteventclasses/onmessage.py

- add a reaction for 6/6
- add yellows reaction
- add greens reaction

#258 - Add further wordle reactions

---

discordbot/betmanager.py
discordbot/bot_enums.py
discordbot/commandmanager.py
discordbot/selects/pledge.py
discordbot/slashcommandeventclasses/__init__.py
discordbot/slashcommandeventclasses/close.py
discordbot/slashcommandeventclasses/king_rename.py
discordbot/slashcommandeventclasses/pledge.py
discordbot/slashcommandeventclasses/taxrate.py
discordbot/tasks/eddiegains.py
discordbot/tasks/eddiekingtask.py
discordbot/tasks/guildchecker.py
discordbot/tasks/revolutiontask.py
discordbot/views/__init__.py
discordbot/views/pledge.py
discordbot/views/revolution.py
discordbot/views/taxrate.py
mongo/baseclass.py
mongo/bsedataclasses.py
mongo/bsepoints.py
mongo/bseticketedevents.py
mongo/datatypes.py
mongo/interface.py

- #269: Began using `@silent` for some messages
- #271: Use Guilds collection for various guild metrics
- #272: Add command to allow "pledging support the King"
- #268: Supporters should get taxed less
- #136: Revolution reminders should be replies
- #80: Revolution shouldn't trigger when King is young

Various changes

---

discordbot/slashcommandeventclasses/king_rename.py

fix for rename was always tagging the king user

#279 - Fix issue with role rename

---

discordbot/selects/bet.py

Fix select option being too long with the title

#305 - Place command not working

---

discordbot/main.py
discordbot/utilities.py

Add colour formatting for logging. This _only_ affects when running locally. But pretty.
Additionally, move the logging setup into `utilities.py` to make `main.py` a bit cleaner.

Colour formatter

---

discordbot/clienteventclasses/onready.py
discordbot/main.py
discordbot/tasks/guildchecker.py

Switch to using "global commands" rather than guild commands

#79 - Actually make commands work for multiple guilds

---

discordbot/betmanager.py
discordbot/bot_enums.py
discordbot/clienteventclasses/baseeventclass.py
discordbot/clienteventclasses/onmemberjoin.py
discordbot/clienteventclasses/onmemberleave.py
discordbot/slashcommandeventclasses/admin_give.py
discordbot/slashcommandeventclasses/close.py
discordbot/slashcommandeventclasses/gift.py
discordbot/slashcommandeventclasses/king_rename.py
discordbot/slashcommandeventclasses/place.py
discordbot/stats/awardsbuilder.py
discordbot/stats/statsdatacache.py
discordbot/tasks/eddiegains.py
discordbot/tasks/eddiekingtask.py
discordbot/tasks/guildchecker.py
discordbot/tasks/revolutiontask.py
discordbot/views/bless.py
discordbot/views/pledge.py
discordbot/views/revolution.py
discordbot/views/taxrate.py
mongo/bsepoints/activities.py
mongo/bsepoints/bets.py
mongo/bsepoints/points.py
mongo/bsepoints/transactions.py
mongo/datatypes.py

- Add collection classes for transactions and activities
- Replace previous usage to new usage
- Simplify some logic so that the `increment_points` function handles the transaction adding
- remove `decrement_points` and just make sure we use `increment_points` with the amount made negative

#336 - Make transactions and activities use a separate collection

---

mongo/baseclass.py
mongo/interface.py

Quick fix for not being able to create new database threads. This is the recommended way to do it anyway.

Mongo cached client fix

---

.github/workflows/build_and_push.yml
.github/workflows/build_and_test.yml
Dockerfile
discordbot/main.py
discordbot/tasks/eddiekingtask.py
discordbot/tasks/guildchecker.py
mongo/baseclass.py
mongo/interface.py

This PR turns our one workflow into two:
- one for pushes to main branch
- one for PRs merging _into_ main branch
The former is what you'd expect; builds the Docker Image and pushes it to the Docker registry.
The latter actually runs an instance of our bot for a few minutes. This then allows us to quickly check the logs and see if any errors occured. This is a pretty basic test: _does our code actually run without errors_? Of course, it's only running for a couple of minutes so won't catch a lot of things but it will instantiate each command class and task class so at the very least we're checking everything for syntax errors. It's the start of some testing we can do to verify that we're not going to break main.
This did actually highlight a couple of _actual_ issues in the startup tasks. …

#339 #130 - CICD changes

---

discordbot/stats/statsclasses.py
discordbot/stats/statsdatacache.py

Fix a couple of bugs with recent stats and awards

Fixing BSEddies bugs

---

discordbot/stats/statsclasses.py
discordbot/tasks/eddiegains.py
discordbot/tasks/wordlereminder.py
discordbot/utilities.py

Convert our start/end stuff when dealing with interactions to UTC aware datetimes so we don't miss messages

Fix bugs with UTC stuff

---

discordbot/selects/revolutionconfig.py
discordbot/tasks/revolutiontask.py
discordbot/views/config.py
discordbot/views/config_revolution.py
mongo/bsepoints/guilds.py
mongo/datatypes.py

Add config option for revolution event; allows disabling/enabling of revolution event

#250 #178 - Add revolution config stuff

---

discordbot/clienteventclasses/onmessage.py
discordbot/message_actions/base.py
discordbot/message_actions/birthday_replies.py
discordbot/message_actions/duplicate_links.py
discordbot/message_actions/marvel_ad.py
discordbot/message_actions/remind_me.py
discordbot/message_actions/thank_you_replies.py
discordbot/message_actions/wordle_reactions.py

Add another message action that memes on lots of people getting 6/6 Wordle scores
Add logger to all the message actions

#402 - Tough one

---

discordbot/stats/awardsbuilder.py
discordbot/stats/statsclasses.py

- Add basics of adding comparisons to previous stats
- Works for a few simple stats
- Not tested yet lol

#109 - Add comparisons to previous stats

---

discordbot/slashcommandeventclasses/bless.py
discordbot/slashcommandeventclasses/pledge.py
discordbot/stats/statsclasses.py

- Fix error with some slash commands not working
- Remove UTC stuff from BSEddies

Some bug fixes

---

discordbot/commandmanager.py
discordbot/tasks/activitychanger.py

This is a basic implementation of an activity task. Randomly picks an activity from the activity options (default weighted higher). If the activity needs a name, it picks one randomly from the list of available options. Can be expanded later to include more dynamic options.

#82 - Create an activity task

---

discordbot/embedmanager.py
discordbot/selects/activitiesconfig.py
discordbot/slashcommandeventclasses/config.py
discordbot/tasks/eddiegains.py
discordbot/tasks/wordletask.py
discordbot/wordle/constants.py
discordbot/wordle/wordlesolver.py

- Fix error on startup with user getting
- Fix indentation level for daily summary message
- Fix typo in config
- Use markdown formatting for main config message
- Fix wordle not working due to new screen

Various bug fixes

---

discordbot/slashcommandeventclasses/taxrate.py

Allows everyone to use `/taxrate` command
Used by 'normal' users; will simply show the tax rate
Used by the 'King'; will also allow them to change the rates

#447 - Allow everyone to use `/taxrate`

---

discordbot/commandmanager.py
discordbot/selects/stats.py
discordbot/slashcommandeventclasses/stats.py
discordbot/slashcommandeventclasses/wordle.py
discordbot/stats/statsdataclasses.py
discordbot/views/stats.py
discordbot/wordle/wordlesolver.py

Adds a `/stats` command for generating some stats. Can choose either quick stats or quick server stats for now.
Add some additional stats to `/wordle` as well.

#137 - Beginnings of a `/stats` command

---

discordbot/clienteventclasses/onmessage.py
discordbot/constants.py
discordbot/message_actions/base.py
discordbot/message_actions/rigged.py
discordbot/tasks/revolutiontask.py
mongo/bsepoints/guilds.py
mongo/datatypes.py

Adds a message action for users that say 'rigged' shortly after a revolution

#446 - Add rigged message action

---

discordbot/slashcommandeventclasses/wordle.py
discordbot/wordle/wordlesolver.py

Resolves #469
Resolves #468
Removes limit on query for wordle messages
Add new dialogue dismiss for daily wordle

#469 #468 Fix wordle bugs

---

discordbot/message_actions/duplicate_links.py
discordbot/tasks/eddiekingtask.py
discordbot/tasks/revolutiontask.py
discordbot/wordle/wordlesolver.py
mongo/bsepoints/generic.py

Closes #462
Reset role names when KING changes for revolutionary/supporter roles
Vary wordle starting word

Fixes and Updates

---

discordbot/stats/awardsbuilder.py

Fix the stat comparisons. Hopefully this will actually show us some data now.

Fix the stats comparisons

---

.gitignore
.pre-commit-config.yaml
discordbot/stats/awardsbuilder.py
discordbot/tasks/activitychanger.py
discordbot/tasks/annualawards.py
discordbot/tasks/betreminder.py
discordbot/tasks/celebrations.py
discordbot/tasks/dailyvallytask.py
discordbot/tasks/eddiekingtask.py
discordbot/tasks/guildchecker.py
discordbot/tasks/wordletask.py
mongo/bsedataclasses.py
ruff.toml

- Prevent awards from repeating entries
- Let wordle task print the words it guessed
- Removed some incorrect bits from comments

Some misc fixes

---

.gitignore
.pre-commit-config.yaml
discordbot/bot_enums.py
discordbot/slashcommandeventclasses/help.py
discordbot/stats/awardsbuilder.py
discordbot/stats/statsclasses.py
discordbot/stats/statsdataclasses.py
discordbot/tasks/betcloser.py
discordbot/utilities.py
discordbot/wordle/wordlesolver.py
mongo/bsedataclasses.py
mongo/bseticketedevents.py
tests/mocks/discord_mocks.py
tests/test_bet_manager.py
tests/test_utilities/test_placeholder_logger.py

Adds two new awards:
- most symmetrical wordles
- most green wordles

#544 - Add additional wordle awards

---

discordbot/views/bless.py
discordbot/views/close.py
discordbot/views/config_activities.py
discordbot/views/config_autogenerate.py
discordbot/views/config_bseddies.py
discordbot/views/config_revolution.py
discordbot/views/config_salary.py
discordbot/views/config_salary_message.py
discordbot/views/config_threads.py
discordbot/views/config_valorant.py
discordbot/views/config_wordle.py
discordbot/views/place.py
discordbot/views/pledge.py
discordbot/views/refresh.py
discordbot/views/stats.py
discordbot/views/taxrate.py
discordbot/views/usergift.py

Catch an additional exception type. `child.values` can now be `None`. Fix for all views.

Fix error with placing bets

---

.pre-commit-config.yaml
discordbot/bot_enums.py
discordbot/stats/awardsbuilder.py
discordbot/stats/statsclasses.py
tests/test_stats/test_stats_classes.py

Adds two new awards:
- most alphabetical messages
- most wordle yellows

Add some additional awards

---

Dockerfile
discordbot/embedmanager.py
discordbot/message_actions/command_suggestion.py
discordbot/modals/activities.py
discordbot/modals/reminder.py
discordbot/modals/suggest.py
discordbot/slashcommandeventclasses/close.py
discordbot/slashcommandeventclasses/place.py
discordbot/slashcommandeventclasses/wordle.py
discordbot/stats/awardsbuilder.py
discordbot/stats/statsclasses.py
discordbot/tasks/dailyvallytask.py
discordbot/tasks/wordletask.py
discordbot/views/config_activities.py
mongo/bsedataclasses.py

It's that time of the month again! Fix some recents errors with the awards.

Fix some awards errors

---

discordbot/clienteventclasses/onreactionadd.py
mongo/bsedataclasses.py

Fix an error with awards
Fix an error with emojis

Fix some more errors

---

.pre-commit-config.yaml
discordbot/constants.py
discordbot/message_actions/wordle_reactions.py

- Take in account commas for wordle messages
- Fix an issue with the tough day message

Wordle Fixes

---

.dockerignore
.github/workflows/build_and_push.yml
.github/workflows/build_and_test.yml
.github/workflows/linting.yml
Dockerfile
README.md
discordbot/main.py
discordbot/utilities.py
sonar-project.properties
update.sh

- Remove credentials from image
- Remove build args
- Update workflows to use environment variables for running
- Add some logging regarding flags and tokens
- Update log rotation values
- Update the `update.sh` script to mount a local `.env` and mount the logs  directory so we can persist logs too
- Update README.md

#579 - Remove credentials from Docker image

---

discordbot/tasks/activitychanger.py
discordbot/tasks/annualawards.py
discordbot/tasks/basetask.py
discordbot/tasks/betcloser.py
discordbot/tasks/betreminder.py
discordbot/tasks/celebrations.py
discordbot/tasks/dailyvallytask.py
discordbot/tasks/eddiegains.py
discordbot/tasks/eddiekingtask.py
discordbot/tasks/guildchecker.py
discordbot/tasks/messagesync.py
discordbot/tasks/monthlyawards.py
discordbot/tasks/reminders.py
discordbot/tasks/revolutiontask.py
discordbot/tasks/taskmanager.py
discordbot/tasks/threadmutetask.py
discordbot/tasks/wordlereminder.py
discordbot/tasks/wordletask.py

Improve the task manager to actually disable/enable tasks when they're not required.
- Define a `TaskSchedule` class for defining when a task should run.
- Task Manager will check each task to see if it matches the schedule - disabling those that aren't needed and enable those that do
- Have an 'overriden' property which allows us to trigger a task despite it's schedule
- Set schedules for each task
- Set default status of tasks to not started
- Set loop count to 1 for infrequent tasks - preventing them running accidentally multiple times

#390 - A better task manager

---

.pre-commit-config.yaml
discordbot/clienteventclasses/onmessage.py
discordbot/constants.py
discordbot/contextcommands/base.py
discordbot/message_actions/alphabetical_reactions.py
discordbot/stats/awardsbuilder.py
discordbot/views/config.py
tests/test_message_actions/test_alphabetical_reactions.py

- update to add a message reaction for alphabetical messages
- add `alphabetical` message type and eddies award
- add tests for it

Add alphabetical reactions

---

.github/workflows/build_and_push.yml
.github/workflows/build_and_test.yml

Change to a public docker repo. This is a fresh repo without any old images in.

Change to public docker repo

---

discordbot/bot_enums.py
discordbot/commandmanager.py
discordbot/embedmanager.py
discordbot/tasks/basetask.py
discordbot/tasks/revolutionbribestask.py
discordbot/tasks/revolutiontask.py
discordbot/views/revolutionbribeview.py
mongo/bseticketedevents.py
mongo/datatypes/revolution.py
tests/test_embed_manager/test_revolution_bribe_embed.py
tests/test_tasks/test_revolution_bribe_task.py
tests/test_tasks/test_revolution_task.py
tests/test_views/test_revolution_bribe_view.py

Add a system that allows the user to bribe the bot into reducing the chance of a revolution.
This is only offered to the user if:
- high chance of losing
- they can't afford to 'save thyself' without losing the King title
- they haven't already saved themselves
- they haven't been King for more than a month
- they aren't in the top 2 for longest Kings
They get the choice of accepting or refusing the offer.

#578 - Add Revolution Bribes

---

discordbot/selects/bet.py
discordbot/selects/betamount.py
discordbot/selects/betoutcomes.py
discordbot/views/place.py
tests/test_selects/test_bet_amount_select.py
tests/test_selects/test_bet_select.py

Let bet amounts be more dynamic.
Rather than hard-coding all the amounts - try and generate some that are more dynamic so that they scale with the eddies the users actually have.

#550 - Dynamic Bet Amounts

---

.github/workflows/check_output_log.py
.github/workflows/ci.yml

Ensure that we are actually checking for errors after we run the BSEBot container for a couple of minutes.

ci: fix CI issues
